export enum InputNames {
  ownerId = "ownerId",
  position = "position",
  deadLineDate = "deadLineDate",
  description = "description",
  startDate = "startDate",
  endDate = "endDate",
  currency = "currency",
  weeklyWorkHours = "weeklyWorkHours",
  freelance = "freelance",
  freelanceHoursPerProject = "freelance.hoursPerProject",
  freelanceHourlyBudgetFrom = "freelance.hourlyBudget.from",
  freelanceHourlyBudgetTo = "freelance.hourlyBudget.to",
  freelanceMonthlyBudgetFrom = "freelance.monthlyBudget.from",
  freelanceMonthlyBudgetTo = "freelance.monthlyBudget.to",
  permanent = "permanent",
  permanentMonthlyBudgetFrom = "permanent.monthlyBudget.from",
  permanentMonthlyBudgetTo = "permanent.monthlyBudget.to",
  yearExperience = "yearExperience",
  yearExperienceFrom = "yearExperience.from",
  yearExperienceTo = "yearExperience.to",
  isUrgent = "isUrgent",
  workingHourTypes = "workingHourTypes",
  workTypes = "workTypes",
  assignedEmployees = "assignedEmployees",
  skills = "skills",
  industries = "industries",
  seniorities = "seniorities",
  languages = "languages",
  formats = "formats",
  isPriority = "isPriority",
}

export default InputNames;
