# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_STATIC_WEB_APPS_API_TOKEN with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. Change the values for the APP_LOCATION, API_LOCATION and APP_ARTIFACT_LOCATION, AZURE_STATIC_WEB_APPS_API_TOKEN environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: Build and deploy to Sand

on:
  workflow_dispatch:

env:
  APP_LOCATION: "/" # location of your client code
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SAND }} # secret containing deployment token for your static web app

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}        
        env:
          REACT_APP_BACKOFFICE_API: "https://app-mm-back-office-sand.azurewebsites.net"
          REACT_APP_BACKOFFICE_APP_ID: "5b69cba7-c95c-4769-8a5d-af0886130a3b"
          REACT_APP_BACKOFFICE_TENANT_ID: "baeb372e-3535-4dcd-b14f-898ade9a376b"
          REACT_APP_BACKOFFICE_SCOPE: "api://app-mm-back-office-sand/BackOffice.User"
          REACT_APP_PAGE_SIZE: 15
          REACT_APP_COMPONENT_ITEMS_PAGE_SIZE: 15
          REACT_APP_PUBLIC_WEBSITE: "https://marchermarholt-public.com"
          REACT_APP_SELFSERVICE_WEBSITE: "https://salmon-grass-044ebcf03.1.azurestaticapps.net"
          REACT_APP_AUTOCOMPLETE_GEOCODER_API: "https://autocomplete.geocoder.ls.hereapi.com"
          REACT_APP_GEOCODER_API_KEY: ${{ secrets.GEOCODER_API_KEY }}
          REACT_APP_WEAVY_API: "https://marcher-markholt.weavycloud.com"
